/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.panel;

public final class R {
    public static final class attr {
        /**  Defines panel animation duration in ms. 
         <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int animationDuration=0x7f010000;
        /**  Defines closed handle (drawable/color). 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int closedHandle=0x7f010004;
        /**  Defines if flying gesture forces linear interpolator in animation. 
         <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int linearFlying=0x7f010002;
        /**  Defines opened handle (drawable/color). 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int openedHandle=0x7f010003;
        /**  Defines panel position on the screen. 
         <p>Must be one of the following constant values.</p>
<table border="2" width="85%" align="center" frame="hsides" rules="all" cellpadding="5">
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant<th>Value<th>Description</tr>
<tr><th><code>top</code><td>0<td> Panel placed at top of the screen. </tr>
<tr><th><code>bottom</code><td>1<td> Panel placed at bottom of the screen. </tr>
<tr><th><code>left</code><td>2<td> Panel placed at left of the screen. </tr>
<tr><th><code>right</code><td>3<td> Panel placed at right of the screen. </tr>
</table>
         */
        public static final int position=0x7f010001;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int transitionDrawable=0x7f010005;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int transitionDrawableLength=0x7f010006;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int transitionTextColorDown=0x7f010008;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int transitionTextColorUp=0x7f010007;
    }
    public static final class drawable {
        public static final int bottom_switcher_collapsed=0x7f020000;
        public static final int bottom_switcher_collapsed_background=0x7f020001;
        public static final int bottom_switcher_collapsed_focused=0x7f020002;
        public static final int bottom_switcher_collapsed_selected=0x7f020003;
        public static final int bottom_switcher_expanded=0x7f020004;
        public static final int bottom_switcher_expanded_background=0x7f020005;
        public static final int bottom_switcher_expanded_focused=0x7f020006;
        public static final int bottom_switcher_expanded_selected=0x7f020007;
        public static final int button_test0=0x7f020008;
        public static final int button_test1=0x7f020009;
        public static final int button_test2=0x7f02000a;
        public static final int button_test3=0x7f02000b;
        public static final int button_test4=0x7f02000c;
        public static final int button_test5=0x7f02000d;
        public static final int button_test6=0x7f02000e;
        public static final int button_test7=0x7f02000f;
        public static final int icon=0x7f020010;
        public static final int left_switcher_collapsed=0x7f020011;
        public static final int left_switcher_collapsed_background=0x7f020012;
        public static final int left_switcher_collapsed_focused=0x7f020013;
        public static final int left_switcher_collapsed_selected=0x7f020014;
        public static final int left_switcher_expanded=0x7f020015;
        public static final int left_switcher_expanded_background=0x7f020016;
        public static final int left_switcher_expanded_focused=0x7f020017;
        public static final int left_switcher_expanded_selected=0x7f020018;
        public static final int right_switcher_collapsed=0x7f020019;
        public static final int right_switcher_collapsed_background=0x7f02001a;
        public static final int right_switcher_collapsed_focused=0x7f02001b;
        public static final int right_switcher_collapsed_selected=0x7f02001c;
        public static final int right_switcher_expanded=0x7f02001d;
        public static final int right_switcher_expanded_background=0x7f02001e;
        public static final int right_switcher_expanded_focused=0x7f02001f;
        public static final int right_switcher_expanded_selected=0x7f020020;
        public static final int top_switcher_collapsed=0x7f020021;
        public static final int top_switcher_collapsed_background=0x7f020022;
        public static final int top_switcher_collapsed_focused=0x7f020023;
        public static final int top_switcher_collapsed_selected=0x7f020024;
        public static final int top_switcher_expanded=0x7f020025;
        public static final int top_switcher_expanded_background=0x7f020026;
        public static final int top_switcher_expanded_focused=0x7f020027;
        public static final int top_switcher_expanded_selected=0x7f020028;
        public static final int transition_list=0x7f020029;
    }
    public static final class id {
        public static final int bottom=0x7f040001;
        public static final int bottomPanel=0x7f040009;
        public static final int left=0x7f040002;
        public static final int leftPanel1=0x7f04000a;
        public static final int leftPanel2=0x7f04000b;
        public static final int panelContent=0x7f040005;
        public static final int panelHandle=0x7f040004;
        public static final int right=0x7f040003;
        public static final int rightPanel=0x7f04000c;
        public static final int smoothButton1=0x7f040007;
        public static final int smoothButton2=0x7f040008;
        public static final int top=0x7f040000;
        public static final int topPanel=0x7f040006;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
    }
    public static final class styleable {
        /** Attributes that can be used with a Panel.
           <p>Includes the following attributes:</p>
           <table border="2" width="85%" align="center" frame="hsides" rules="all" cellpadding="5">
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute<th>Summary</tr>
           <tr><th><code>{@link #Panel_animationDuration org.panel:animationDuration}</code><td> Defines panel animation duration in ms.</tr>
           <tr><th><code>{@link #Panel_closedHandle org.panel:closedHandle}</code><td> Defines closed handle (drawable/color).</tr>
           <tr><th><code>{@link #Panel_linearFlying org.panel:linearFlying}</code><td> Defines if flying gesture forces linear interpolator in animation.</tr>
           <tr><th><code>{@link #Panel_openedHandle org.panel:openedHandle}</code><td> Defines opened handle (drawable/color).</tr>
           <tr><th><code>{@link #Panel_position org.panel:position}</code><td> Defines panel position on the screen.</tr>
           </table>
           @see #Panel_animationDuration
           @see #Panel_closedHandle
           @see #Panel_linearFlying
           @see #Panel_openedHandle
           @see #Panel_position
         */
        public static final int[] Panel = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004
        };
        /**
          <p>
          @attr description
           Defines panel animation duration in ms. 


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android:animationDuration
        */
        public static final int Panel_animationDuration = 0;
        /**
          <p>
          @attr description
           Defines closed handle (drawable/color). 


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          <p>This is a private symbol.
          @attr name android:closedHandle
        */
        public static final int Panel_closedHandle = 4;
        /**
          <p>
          @attr description
           Defines if flying gesture forces linear interpolator in animation. 


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name android:linearFlying
        */
        public static final int Panel_linearFlying = 2;
        /**
          <p>
          @attr description
           Defines opened handle (drawable/color). 


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          <p>This is a private symbol.
          @attr name android:openedHandle
        */
        public static final int Panel_openedHandle = 3;
        /**
          <p>
          @attr description
           Defines panel position on the screen. 


          <p>Must be one of the following constant values.</p>
<table border="2" width="85%" align="center" frame="hsides" rules="all" cellpadding="5">
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant<th>Value<th>Description</tr>
<tr><th><code>top</code><td>0<td> Panel placed at top of the screen. </tr>
<tr><th><code>bottom</code><td>1<td> Panel placed at bottom of the screen. </tr>
<tr><th><code>left</code><td>2<td> Panel placed at left of the screen. </tr>
<tr><th><code>right</code><td>3<td> Panel placed at right of the screen. </tr>
</table>
          <p>This is a private symbol.
          @attr name android:position
        */
        public static final int Panel_position = 1;
        /** Attributes that can be used with a SmoothButton.
           <p>Includes the following attributes:</p>
           <table border="2" width="85%" align="center" frame="hsides" rules="all" cellpadding="5">
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute<th>Summary</tr>
           <tr><th><code>{@link #SmoothButton_transitionDrawable org.panel:transitionDrawable}</code><td></tr>
           <tr><th><code>{@link #SmoothButton_transitionDrawableLength org.panel:transitionDrawableLength}</code><td></tr>
           <tr><th><code>{@link #SmoothButton_transitionTextColorDown org.panel:transitionTextColorDown}</code><td></tr>
           <tr><th><code>{@link #SmoothButton_transitionTextColorUp org.panel:transitionTextColorUp}</code><td></tr>
           </table>
           @see #SmoothButton_transitionDrawable
           @see #SmoothButton_transitionDrawableLength
           @see #SmoothButton_transitionTextColorDown
           @see #SmoothButton_transitionTextColorUp
         */
        public static final int[] SmoothButton = {
            0x7f010005, 0x7f010006, 0x7f010007, 0x7f010008
        };
        /**
          <p>This symbol is the offset where the {@link org.panel.R.attr#transitionDrawable}
          attribute's value can be found in the {@link #SmoothButton} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name android:transitionDrawable
        */
        public static final int SmoothButton_transitionDrawable = 0;
        /**
          <p>This symbol is the offset where the {@link org.panel.R.attr#transitionDrawableLength}
          attribute's value can be found in the {@link #SmoothButton} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:transitionDrawableLength
        */
        public static final int SmoothButton_transitionDrawableLength = 1;
        /**
          <p>This symbol is the offset where the {@link org.panel.R.attr#transitionTextColorDown}
          attribute's value can be found in the {@link #SmoothButton} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:transitionTextColorDown
        */
        public static final int SmoothButton_transitionTextColorDown = 3;
        /**
          <p>This symbol is the offset where the {@link org.panel.R.attr#transitionTextColorUp}
          attribute's value can be found in the {@link #SmoothButton} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:transitionTextColorUp
        */
        public static final int SmoothButton_transitionTextColorUp = 2;
    };
}
