#!/bin/sh

# Generate the included table for the master README file

FNAME_README=README.1line.txt
FNAME_STATUS=STATUS.1line.txt

for d in *
do
	if [ -d $d ]; then
		BUILDS_WITH=""
		if [ -f $d/${FNAME_README} ]; then
			FUNCTION=$(cat $d/${FNAME_README})
			if [ -f $d/${FNAME_STATUS} ]; then
				NOTES=$(cat $d/${FNAME_STATUS})
			else
				NOTES="-"
			fi
			if [ -f $d/.project ]; then BUILDS_WITH+=E; fi
			if [ -f $d/pom.xml ]; then BUILDS_WITH+=M; fi
			if [ -f $d/build.gradle -o -f $d/app/build.gradle ]; then BUILDS_WITH+=G; fi
			if [ -f $d/$d.iml -o -f $d/app/$d.iml ]; then BUILDS_WITH+=S; fi
			echo '|' "link:https://github.com/IanDarwin/Android-Cookbook-Examples/tree/master/$d[$d]" '|' $BUILDS_WITH '|' $FUNCTION '|' ${NOTES}
		else
			echo "$d has no ${FNAME_README}" >&2
		fi
	fi
done |
	 grep -v _ | # Strip compat_v7 etc
		sort -f -t'[' -k2 # sort on link[Name]

