/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class foo_ndkdemo_SqrtDemo */

#ifndef _Included_foo_ndkdemo_SqrtDemo
#define _Included_foo_ndkdemo_SqrtDemo
#ifdef __cplusplus
extern "C" {
#endif
#undef foo_ndkdemo_SqrtDemo_EPSILON
#define foo_ndkdemo_SqrtDemo_EPSILON 0.05
/*
 * Class:     foo_ndkdemo_SqrtDemo
 * Method:    sqrtC
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_foo_ndkdemo_SqrtDemo_sqrtC
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
